# fly.toml file generated for phonebook-cicd on 2023-03-12T14:05:43+01:00

app = "phonebook-cicd"

[env]
  PORT = "8080" # add this 3001

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080 
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    [services.http_checks.headers]
  
  [[services.script_checks]]
    command = "/app/health_check.sh"
    args = []
    grace_period = "2s"
    interval = "10s"
    restart_limit = 0
    timeout = "1s"